# Generated by Django 5.1.4 on 2024-12-29 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_criteria_added_by_company_criteria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criteria',
            old_name='title',
            new_name='label',
        ),
    ]
